### ISSUE TITLE
CJS + ESM Builds

### ISSUE THREAD

**Issue by BusinessDuck** [vitalets/tinkoff-invest-api#1]
Для корректной работы требуется 2 вида сборок, сконфигурируй сборщик по образу и подобию дебюта
Используй в package.json что-то типо того, чтобы мог работать как require c commonjs так и модульная архитектура.

Пример настроек в package.json
```typescript
  "main": "lib/index.js",
    "module": "lib/index.js",
    "types": "lib/index.d.ts",
```

более современный подход через `exports` тут https://antfu.me/posts/publish-esm-and-cjs

**Comment by vitalets** [comment]
Можно конечно собрать. 
А поделись детальнее, где у тебя не заводится, чтобы я смог проверить?
В целом тренд на то, чтобы не поддерживать cjs. Это лишние артефакты, плюс потенциальный [dual package hazard](https://nodejs.org/api/packages.html#packages_dual_package_hazard). Кажется, не осталось [непреодолимых кейсов](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). А рано или поздно понадобится какой-нибудь [node-fetch](https://github.com/node-fetch/node-fetch), который уже тоже esm only.

На счет pm2 я еще в 2020 у них в тикете [проверял](https://github.com/Unitech/pm2/issues/4540#issuecomment-574027194), что все работает. 

Может попробуем дебют в esm завести?)

**Comment by BusinessDuck** [comment]
https://github.com/Unitech/pm2/issues/4540

предположительно этот тред про esm совместимость

**Comment by BusinessDuck** [comment]
> Можно конечно собрать. 
> 
> А поделись детальнее, где у тебя не заводится, чтобы я смог проверить?
> 
> В целом тренд на то, чтобы не поддерживать cjs. Это лишние артефакты, плюс потенциальный [dual package hazard](https://nodejs.org/api/packages.html#packages_dual_package_hazard). Кажется, не осталось [непреодолимых кейсов](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c). А рано или поздно понадобится какой-нибудь [node-fetch](https://github.com/node-fetch/node-fetch), который уже тоже esm only.
> 
> 
> 
> На счет pm2 я еще в 2020 у них в тикете [проверял](https://github.com/Unitech/pm2/issues/4540#issuecomment-574027194), что все работает (хотя ниже там в комментах не у всех работает и сам тикет открыт до сих пор). 
> 
> 
> 
> Может попробуем дебют в esm завести?)

попробую сегодня, теоретически это может и ускорить его даже

**Comment by BusinessDuck** [comment]
Попробовал мигрировать и куча проблем сразу вылезло
1 . TS не компилирует с расширением импорты `import { foo } from './bar.js'`
2. ts-node и pm2 если и смогут запустить то очень костыльно
3. Прочитал статью про интеграцию esm которую ты скидывал, там почти все пункты начинаются со слов "проблема с ..." 

Увы это точно не продакшин уровень, не буду пока мигрировать, когда `--experimental-modules` заупстят, тогда можно начинать уже

**Comment by vitalets** [comment]
Ок, собираем cjs тогда!

**Comment by vitalets** [comment]
Собрал версию с поддержкой cjs. Установить можно через `npm i tinkoff-invest-api@next`
Также надо обновить ts и vscode до последних версий.

Проблемы вылезли для subpath, через который экспортятся все тиньковские типы.

Если в `tsconfig.json` оставить `"moduleResolution": "node"`, то VSCode не видит package.exports и предлагает некорректные пути (а корректный `tinkoff-invest-api/generated` наоборот не предлагает):
![image](https://user-images.githubusercontent.com/1473072/173230493-18924ef3-817f-444b-93a0-da98a4959d87.png)

А если вручную исправить пути на `tinkoff-invest-api/generated/marketdata`,  ts ругается, что типов не обнаружено:
![image](https://user-images.githubusercontent.com/1473072/173231674-08915567-82c2-45e0-b2bc-02e4ea214860.png)
Код не запускается.

Если в `tsconfig.json` поставить новый `"moduleResolution": "nodenext"`, то VSCode вариантов вообще не предлагает:
![image](https://user-images.githubusercontent.com/1473072/173232879-3c1285f4-bbf8-4753-b8a8-b8ab2a0be2bb.png)

Зато код запускается :)

С не-subpath импортами все хорошо:
![image](https://user-images.githubusercontent.com/1473072/173233103-61d2f6fd-b07f-4e17-b68c-e0870f9f54f1.png)

[Пишут](https://github.com/microsoft/TypeScript/issues/33079#issuecomment-1141801839), что поддержки subpath в ближайшее время не будет. Вот еще [тикет в репе тайпскрипта](https://github.com/microsoft/TypeScript/issues/48652).

@BusinessDuck попробуй у себя эту версию. И напиши что как.

**Comment by BusinessDuck** [comment]
Получилось запустить, `exports` корректно не работают, пока лучше их вообще убрать, с ними не собирается финальный модуль в стратегиях уже, говорит что пути `/dist/` в них не прописаны либо вообще забить пока, либо все же сделать ручками экспорт

**Comment by BusinessDuck** [comment]
Сейчас запушу ядро, там можно собрать с репозиторием Strategies слинковать и поиграться запросами истории командой `npm run compile && npm run testing -- --bot=FTBot --ticker=TSLA --days=10 --visualize`

```
path: '/tinkoff.public.invest.api.contract.v1.InstrumentsService/GetInstrumentBy',
  code: 16,
  details: 'Authentication failed',
  trackingId: '5e02342fdc95b8c7528cbd8e1cdbe28b',
  envoyUpstreamServiceTime: '8',
  ratelimit: '200, 200;w=60',
  ratelimitRemaining: '199',
  ratelimitReset: '199'
```

**Comment by BusinessDuck** [comment]
Запросы истории заработали, перевыпустил токен, видимо со старым что-то не так было

**Comment by vitalets** [comment]
Хотел вручную зареэкспортить все типы из Тинькофф, там тоже проблемка, т.к. есть дублирующиеся экспорты:
![image](https://user-images.githubusercontent.com/1473072/173360467-54cc9aa9-dc7c-4b89-a066-d0f916d349b0.png)

Перечислять явно все типы совсем не хочется.
Тогда остается вариант перечислить эти файлы в package.exports:
```
    "./marketdata": {
      "import": "./dist/generated/marketdata.js",
      "require": "./cjs/generated/marketdata.js"
    },
```
И тогда импорты будут выглядеть так:
```ts
import { CandleInterval } from 'tinkoff-invest-api/marketdata';
```
В принципе довольно лаконично получается.
@BusinessDuck Что скажешь?

> exports корректно не работают, пока лучше их вообще убрать

Ты имеешь ввиду вообще секцию exports убрать или только часть про Тинькофф типы?

**Comment by BusinessDuck** [comment]
если все как ты в последнем сообщении предложил заработает - то можно оставлять, сделай с таким перечислением релиз и я проверю. На моей стороне проблема была когда есть exports в package.json, а я импортирую из /dist/ директории, там ругался толи тайпскрипт толи нода сама.

**Comment by vitalets** [comment]
Новая версия выехала.
Импорты доступны так:
```ts
import { CandleInterval } from 'tinkoff-invest-api/marketdata';
```
Тег тот же:
```
npm i tinkoff-invest-api@next
```

@BusinessDuck

**Comment by BusinessDuck** [comment]
4.7 TypeScript примерно такой синтаксис требует

```json
// package.json
{
    "name": "my-package",
    "type": "module",
    "exports": {
        ".": {
            // Entry-point for `import "my-package"` in ESM
            "import": {
                // Where TypeScript will look.
                "types": "./types/esm/index.d.ts",

                // Where Node.js will look.
                "default": "./esm/index.js"
            },
            // Entry-point for `require("my-package") in CJS
            "require": {
                // Where TypeScript will look.
                "types": "./types/commonjs/index.d.cts",

                // Where Node.js will look.
                "default": "./commonjs/index.cjs"
            },
        }
    },

    // Fall-back for older versions of TypeScript
    "types": "./types/index.d.ts",

    // CJS fall-back for older versions of Node.js
    "main": "./commonjs/index.cjs"
}
```

**Comment by BusinessDuck** [comment]
При любом исходе стоит добавить еще `"types": "./cjs/index.d.ts"` в `package.json` а то бывает не находит типы автомагически.

**Comment by BusinessDuck** [comment]
Попробовал `typescript 4.7` и даже так `npm install typescript@beta`, руками прописал в `package.json` все что нужно и не завелось

```
error TS2307: Cannot find module 'tinkoff-invest-api/marketdata' or its corresponding type declarations.

7 import { CandleInterval } from 'tinkoff-invest-api/marketdata';
```

**Comment by vitalets** [comment]
Резюмирую сюда, что обсудили в тг.

Если не использовать `"module": "NodeNext"`, тогда ts ругается на tinkoff-invest-api
```
Cannot find module 'tinkoff-invest-api/marketdata' or its corresponding type declarations.
```

Если использовать `"module": "NodeNext"`, тогда ts ругается на другие библиотеки (`@master-chief/alpaca`).

Решили совсем убрать `package.exports` и оставить только `main` и `module`. Соответственно импорты в cjs будут такие:
```ts
import { TinkoffInvestApi } from 'tinkoff-invest-api';
import { CandleInterval } from 'tinkoff-invest-api/cjs/generated/marketdata';
```

Выложил версию, @BusinessDuck проверяй :)

**Comment by BusinessDuck** [comment]
Все работает, можно релизить ;)

**Comment by vitalets** [comment]
Зарелизил 4.0.0 с поддержкой cjs.

**Comment by vitalets** [comment]
Заодно завел тикет в @master-chief/alpaca https://github.com/117/alpaca/issues/106
