### ISSUE TITLE
Не могу  создать ордер

### ISSUE THREAD

**Issue by CruzedV** [vitalets/tinkoff-invest-api#12]
Передаю в параметры orderId строку: 
![image](https://user-images.githubusercontent.com/48482781/229063422-66f2b4fc-f7d5-466a-8352-8072e2e68c0e.png)
Также, я пробовал: 
![image](https://user-images.githubusercontent.com/48482781/229063709-b6b9d017-689f-414c-b87b-b13ceae481b5.png)

Но в консоль выдает это:
![image](https://user-images.githubusercontent.com/48482781/229063073-de20070e-7e9b-4aca-b271-e89ac63b6f6b.png)

Я не знаю куда обратиться, чтобы получить помощь

**Comment by Dennis-Nedry-From-Jurassic-Park** [comment]
@CruzedV попробуй для orderId заменить код на такой:

```js

import {v4 as uuidv4} from 'uuid';

orderId: uuidv4(),
```

для accountId вынести в отдельную переменную + поставить await

примерно так :
```js
const account = await (await api.users.getAccounts({})).accounts.filter(it => it.name === 'Брокерский счёт')[0];
console.log(account);
console.log(account.id);
```

а лучше вынести просто в объект или енум эти айдишники, не дёргать лишний раз

**Comment by vitalets** [comment]
Да, какого-то поля не хватает. Скорее всего аккаунта, как выше написал @Dennis-Nedry-From-Jurassic-Park.
Попробуй еще в консоль вывести весь объект, который в postOrder передается.

**Comment by CruzedV** [comment]
Спасибо, вы мне очень помогли. Действительно поле аккаунта было пустым.
