### ISSUE TITLE
Не нашёл информации про обработку ошибок

### ISSUE THREAD

**Issue by devoln** [vitalets/tinkoff-invest-api#14]
Если превышен лимит на количество запросов в минуту, нужно самому обрабатывать эту ситуацию или библиотека сама повторит запрос с нужной задержкой?
Если самому, то как извлечь нужную информацию об ошибке? Например о том, что это именно rate limit ошибка, а также время, когда можно выполнить повторный запрос.
Предполагаю, что при ошибке будет reject у Promise. Соответственно, await выбросит исключение, но как узнать, какие поля будут у этого исключения?

Думаю, стоит добавить в ReadMe информацию об обработке ошибок.

**Comment by vitalets** [comment]
[Вот тут](https://github.com/vitalets/tinkoff-invest-api/blob/b4dcad3251e120f84a7fbff0d75084aed732df95/src/api-error.ts#L54) происходит оборачивание ответа апи в ошибку и как раз добавляется значения rateLImit.

**Comment by devoln** [comment]
А здесь не опечатка случайно? Двум полям один и тот же хедер присваивается.
```javascript
error.ratelimitRemaining = metadata.get('x-ratelimit-remaining') || '';
error.ratelimitReset = metadata.get('x-ratelimit-remaining') || '';
```

**Comment by Dennis-Nedry-From-Jurassic-Park** [comment]
@vitalets 
правильно понимаю что доступ к ошибке можно получить только так ?

```ts
api.stream.market.trades({ instruments: robot.instruments },  (trade:any) => {
     console.log(trade);
}).catch((err: TinkoffApiError) => {
     console.log(err.ratelimit + '');
})
```

**Comment by vitalets** [comment]
> @vitalets правильно понимаю что доступ к лимитам ratelimit/ratelimitRemaining можно получить только так ?
> 
> ```ts
> api.stream.market.trades({ instruments: robot.instruments },  (trade:any) => {
>      console.log(trade);
> }).catch((err: TinkoffApiError) => {
>      console.log(err.ratelimit + '');
> })
> ```

Насколько я помню, и в случае успешного запроса к ответу прикрепляется текущее значение ratelimitRemaining.
Вот только как его достать сходу не подскажу, надо потрейсить код

**Comment by vitalets** [comment]
Опечатка исправлена в 7.0.1.
