### ISSUE TITLE
Type Exports 

### ISSUE THREAD

**Issue by BusinessDuck** [vitalets/tinkoff-invest-api#2]
Необходимо пробросить типы экспортируемых сущностей из корня. С помощью `package.json` поля `exports` сделать такой контракт
```javascript
import { CandleInterval } from 'tinkoff-invest-api/types';
```
В качестве альтернативы, можно сделать `index.ts` с пробросом экспортов из генерируемых и внутренних файлов протокола API v2, реализация не принципиальна главная задача победить такие импорты
```javascript
import { CandleInterval } from 'tinkoff-invest-api/dist/generated/marketdata';
```

**Comment by vitalets** [comment]
В целом согласен. По неймингу - `tinkoff-invest-api/types` не совсем корректно, там не только типы, но и сгенерированные реализации. Предлагаю `tinkoff-invest-api/proto`.

**Comment by vitalets** [comment]
А может не собирать все в один `index.ts`, а просто делать так:
```ts
import { CandleInterval } from 'tinkoff-invest-api/proto/marketdata';
// vs
import { CandleInterval } from 'tinkoff-invest-api/proto';
```

Просто если реэкспортить все из одной точке, то придется всегда ее вручную синкать с фактически сгенерёнными файлами. Плюс подключаются всегда все файлы: если какой-то модуль например в апи не используется, он все равно будет подключаться. 
Что скажешь?

**Comment by BusinessDuck** [comment]
главное чтобы работало, выглядит ок, посмотрим отработает ли ресолвер пакетов ноды, в любом случае выглядит лучше чем руками добавлять

**Comment by vitalets** [comment]
> главное чтобы работало, выглядит ок, посмотрим отработает ли ресолвер пакетов ноды, в любом случае выглядит лучше чем руками добавлять

А у тебя VSCode? У меня он автоматом эти импорты добавляет.

**Comment by BusinessDuck** [comment]
> > главное чтобы работало, выглядит ок, посмотрим отработает ли ресолвер пакетов ноды, в любом случае выглядит лучше чем руками добавлять
> 
> 
> 
> А у тебя VSCode? У меня он автоматом эти импорты добавляет.

VScode да, он норм работает, а вот ресолвер в роллапе не может найти, хз почему, думаю если экспорты прописать то заработает нормально

**Comment by vitalets** [comment]
> VScode да, он норм работает, а вот ресолвер в роллапе не может найти, хз почему, думаю если экспорты прописать то заработает нормально

А дай шаги, как мне проверить? debut-js/core собрать?

**Comment by BusinessDuck** [comment]
> > VScode да, он норм работает, а вот ресолвер в роллапе не может найти, хз почему, думаю если экспорты прописать то заработает нормально
> 
> А дай шаги, как мне проверить? debut-js/core собрать?

не совсем, нужно еще слинковать с основной библиотекой, ты сделай и выкати с фиксами пакет вот так `npm version prerelease --preid=beta` он скрыто опубликуется и я смогу выкачать и проверить как оно работает

**Comment by BusinessDuck** [comment]
> > > VScode да, он норм работает, а вот ресолвер в роллапе не может найти, хз почему, думаю если экспорты прописать то заработает нормально
> > 
> > 
> > А дай шаги, как мне проверить? debut-js/core собрать?
> 
> не совсем, нужно еще слинковать с основной библиотекой, ты сделай и выкати с фиксами пакет вот так `npm version prerelease --preid=beta` он скрыто опубликуется и я смогу выкачать и проверить как оно работает

я тебе во втором треде описал. если что в ЛС заходи я более подробно распишу

**Comment by BusinessDuck** [comment]
решение и обсуждение перемещено в #1
