### ISSUE TITLE
ошибка "Received message larger than max (4853862 vs. 4194304)"

### ISSUE THREAD

**Issue by kmaximur** [vitalets/tinkoff-invest-api#23]
Данная ошибка возникает при запросе api.instruments.shares()
Нужно добавить в createChannel следующие options:
"grpc.max_receive_message_length": 1024 * 1024 * 100,
"grpc.max_send_message_length": 1024 * 1024 * 100

**Comment by vitalets** [comment]
Поправил в 6.1.0.
Проверьте, пожалуйста.

**Comment by kmaximur** [comment]
> Поправил в 6.1.0. Проверьте, пожалуйста.

Работает, спасибо!
