### ISSUE TITLE
Обновление версии протокола

### ISSUE THREAD

**Issue by Jokky** [vitalets/tinkoff-invest-api#24]
В данный момент тиньк дает версию 1.24, можно ли как-то самостоятельно обновить и опубликовать изменения?

Новый репозиторий документации: https://github.com/RussianInvestments/investAPI

**Comment by vitalets** [comment]
Да, можно попробовать в форке обновить proto-файлы, вот тут обсуждали процесс: https://github.com/vitalets/tinkoff-invest-api/issues/15
Скорее всего будут какие-то ошибки, если что приносите в этот тикет, посмотрим.

**Comment by Jokky** [comment]
Обновил прото в отдельной ветке и возникли следующие ошибки. С первыми двумя еще понятно как разобраться, но проблема есть еще с `candles-loader/req.ts`. В таком случае будет правильно передавать пустую строчку для кэширования?
![12490](https://github.com/user-attachments/assets/f74fe648-d69a-4687-94f4-8a346e618e27)

**Comment by Jokky** [comment]
И еще вопрос, могу ли я запушить ветку в этот репозиторий? Или в любом случае нужен отдельный форк репозитория?

**Comment by Jokky** [comment]
https://github.com/vitalets/tinkoff-invest-api/pull/25

**Comment by vitalets** [comment]
> С первыми двумя еще понятно как разобраться, но проблема есть еще с `candles-loader/req.ts`. В таком случае будет правильно передавать пустую строчку для кэширования?

`instrumentId` либо `figi` всегда должен быть. Поэтому предлагаю так:

```ts
protected getInstrumentKey() {
   const key = this.params.instrumentId || this.params.figi;
   if (!key) throw new Error(`instrumentId or figi is required.`);

   return key;
}
```

**Comment by vitalets** [comment]
Зарелизил 7.0.0.
Спасибо!
