### ISSUE TITLE
Use Cache Parameter

### ISSUE THREAD

**Issue by BusinessDuck** [vitalets/tinkoff-invest-api#3]
Сделай пожалуйста опциональным сохранение кеша. Мне не оч нравится вообще идея кешировать что-то на стороне библиотеки, кажется что это задача внешнего модуля (Just my mind). Если не убирать то хотябы отключить для дебюта, там свой кеш.

https://github.com/vitalets/tinkoff-invest-api/blob/6171ae90e49098b4f075991625a106602206e400/src/candles-loader/req.ts#L43

**Comment by vitalets** [comment]
Если не нужен кеш, то можно напрямую из `api.marketdata.getCandles()` забирать вместо `candlesLoader`. Или тебе нужна разбивка по чанкам, но без кеша? 
Просто разбивка по чанкам (дням) же в дебюте есть.

**Comment by BusinessDuck** [comment]
> Если не нужен кеш, то можно напрямую из `api.marketdata.getCandles()` забирать вместо `candlesLoader`. Или тебе нужна разбивка по чанкам, но без кеша? 
> 
> Просто разбивка по чанкам (дням) же в дебюте есть.

если ты напрямую сделал там, то вопросов нет :) можно закрывать тикет

**Comment by vitalets** [comment]
> если ты напрямую сделал там, то вопросов нет :) можно закрывать тикет

Да, там [напрямую](https://github.com/debut-js/Core/pull/20/files#diff-cbf57f15a4164b9e21ae41a469536daf93d128d24cf04d537c2d31f3eaefcf4eR41) - просто получение свечей с сервера.
