### ISSUE TITLE
Proposal: usage of watch

### ISSUE THREAD

**Issue by BusinessDuck** [vitalets/tinkoff-invest-api#6]
Хочется предложить убрать подписку на событие `data`, и передавать обработчик  в метод `watch(request, callback)` чтобы он был персонализирован также по `figi`

```typescript
const request = { candles: [{ figi, interval }] };
const unsubscribeStream = this.api.stream.market.watch(request, { candle }) => {
    handler(transformTinkoffCandle(candle));
});

return () => {
    this.removeInstrumentFromCache(opts);
    unsubscribeStream();
};
```

**Comment by vitalets** [comment]
А если на несколько figi подписка, то на каждый из них срабатывает коллбэк?
```ts
const request = { candles: [{ figi: 'xxx', interval }, { figi: 'yyy', interval }] };
const unsubscribeStream = this.api.stream.market.watch(request, { candle }) => {
    handler(transformTinkoffCandle(candle));
});
```
По ощущениям это немного не Node.js style

**Comment by BusinessDuck** [comment]
Обсудили в кулуарах, решили попробовать сделать контакт а-ля Binance

**Comment by vitalets** [comment]
Заметил, что в подписках на свечи добавился флаг [waitingClose](https://github.com/Tinkoff/investAPI/blob/ed8330e0def031252f308183c1241f5de01362b4/src/docs/contracts/marketdata.proto#L82), причем на уровне запроса, а не внутри instruments.
Тогда предлагаю такой вариант подписок:
```ts
// подписка на свечи
api.stream.market.candles({ 
  instruments: [ 
    { figi: 'xxx', interval: SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE },
    { figi: 'yyy', interval: SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE },
  ],
  waitingClose: true,
}, ({ candle }) => { ... });

// подписка на сделки
api.stream.market.trades({ instruments: [ { figi: 'xxx' }, { figi: 'yyy' } ]}, ({ trade }) => { ... });
```
Получилось более громоздко чем сейчас и чем [у бинанс](https://github.com/binance-exchange/binance-api-node#candles-1), но автоматом поддерживаем все флаги запросов (в т.ч. будущие).

@BusinessDuck что скажешь?

**Comment by BusinessDuck** [comment]
Выглядит сильно лучше, мне нравится. Я не понял что делает waitingCose, вроде как не начинает отправку событий до закрытия текущей свечи. Это редкий кейс такие параметры можно сделать третьим аргументом и опциональным (поменяй местами с колбеком) тогда для обывателя будет все просто а, для продвинутого использования параметры уже будут

**Comment by vitalets** [comment]
> поменяй местами с колбеком

Предлагаю все-таки оставить waitingCose  в первом аргументе, колбэк как-то привычнее последним аргументом. Да и поддерживать проще, если новые флаги будут появляться.

**Comment by vitalets** [comment]
Я тут еще экспериментировал и понял, что привязки колбэка по figi недостаточно.
Например, если на один figi создается 2 подписки по минуткам и 5-минуткам:
```ts
// подписка на 1-мин свечи
api.stream.market.candles({ 
  instruments: [ { figi: 'xxx', interval: SubscriptionInterval.SUBSCRIPTION_INTERVAL_ONE_MINUTE } ],
}, handler1);

// подписка на 5-мин свечи
api.stream.market.candles({ 
  instruments: [ { figi: 'xxx', interval: SubscriptionInterval.SUBSCRIPTION_INTERVAL_FIVE_MINUTE } ],
}, handler2);
```
Если сравнивать только по figi, то оба хендлера будут срабатывать и на минутки и на 5-минутки.

Похоже, нужно рассчитывать некий id подписки исходя из параметров и сравнивать приходящие эвенты по нему. Для свечей это figi + interval (а по хорошему еще и waitingClose).

@BusinessDuck

**Comment by BusinessDuck** [comment]
Хороший наброс, но думаю что в случае с waitingClose оно так или иначе не сработает если уже есть подписка, тк заново создаваться дополнительный дата канал для этого figi в соединении не будет, тк он уже есть, или будет? Тут наверное бекенд нужно проверить как работает в случае если мы запросили сначала подписку на figi, затем еще раз запросили но уже с доп параметром

**Comment by vitalets** [comment]
Зарелизил `tinkoff-invest-api@next` с typed-emitter в prod dependencies.
Дима, тогда как будут результаты проверки стримов в проде, напиши и зарелизим если все ок.
@BusinessDuck

**Comment by vitalets** [comment]
Пофикшено в https://github.com/vitalets/tinkoff-invest-api/pull/7
