### ISSUE TITLE
Market stream stalled connection

### ISSUE THREAD

**Issue by BusinessDuck** [vitalets/tinkoff-invest-api#9]
Соединение зависает в период отстуствия активности на бдирже, во время после закрытия основной торговой сессии, начинается обмен данными`ping`,  какое-то время он работает, после чего перестает быть всякая активность внутри соединения grpc, при этом само соединение не разрывается судя по логам.
![telegram-cloud-photo-size-2-5469877234027314775-y](https://user-images.githubusercontent.com/10143411/185067501-0d3ae021-1980-4d40-9e59-4d2a7c83282b.jpg)

Мониторинг событий выглядит вот так
![telegram-cloud-photo-size-2-5469877234027314776-y](https://user-images.githubusercontent.com/10143411/185067538-619749f8-215b-40fa-a9da-9f073dc02816.jpg)

**Comment by BusinessDuck** [comment]
@AlexanderVolkovTCS обсуждаем тут пока эту проблему с пингами, сегодня еще раз сделаю более детальное логирование в конце дня, посмотрим какие вообще данные летят. По поводу пингов, мы с @vitalets не нашли кода, где кто-то отвечает на ping. Пока спросим в чатиках пробовал ли кто-то держать коннект более суток и нет ли проблем.

**Comment by vitalets** [comment]
> По поводу пингов, мы с @vitalets не нашли кода, где кто-то отвечает на ping.

Судя по документации, на пинг отвечать не нужно:

> Для сохранения стабильного подключения при отсутствии данных в stream-соединении сервером периодически отправляется ping-пакет. **Клиенту реагировать на него нет необходимости.**

**Comment by vitalets** [comment]
Меня смущают интервалы между пингами, особенно последний - 25 минут. Не слишком долго?
По скриншоту (в минутах): 2, 7, 9, 12, 9, 4, 12, 5, 17, 25

**Comment by vitalets** [comment]
@BusinessDuck Дима, если все ок, давай закроем?

**Comment by BusinessDuck** [comment]
кроем, проблему решили на стороне бэка
